name: Build Docker container

on:
  push:
    branches: [main]

jobs:
  build-push:
    name: Buid and push Docker image to GitHub Container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Extract version and set it to TAG env var
      run: |
        echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        target: final
        push: true
        tags: |
          ghcr.io/mxseev/eliseev.mx:latest
          ghcr.io/mxseev/eliseev.mx:${{ env.TAG }}
          ghcr.io/mxseev/eliseev.mx:$(date +%s)
